In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Input,Dense
import numpy as np

In [4]:
x= np.array([[0,0],[0,1],[1,0],[1,1]],"uint8")
y= np.array([[0],[0],[0],[1]],"uint8")

In [5]:
model= Sequential()

model.add(Dense(units=1, activation='sigmoid',input_dim=2))

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.fit(x, y, epochs=1000)


Epoch 1/1000
1/1 [==============================] - 0s 406ms/step - loss: 0.7171 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7168 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.7165 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.7162 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.7159 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7156 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7153 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.7150 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.7147 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7145 - accuracy: 0.5000
Epoch 11/1000
1/1

In [7]:
print(model.layers[0].get_weights())


[array([[0.8143022 ],
       [0.19868594]], dtype=float32), array([-0.92419994], dtype=float32)]


In [8]:
model.predict(x)

array([[0.28410292],
       [0.32617992],
       [0.4725532 ],
       [0.52218246]], dtype=float32)

In [24]:
x= [[0,0],[0,1],[1,0],[1,1]]
y= [[0],[1],[1],[0]]

In [9]:
xor= Sequential()

xor.add(Dense(2, input_dim=2, activation='sigmoid'))

xor.add(Dense(1, activation='sigmoid'))

xor.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

xor.summary()





Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [10]:
xor.fit(x,y, epochs=5000)

Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.1922 - accuracy: 1.0000
Epoch 2502/5000
1/1 [==============================] - 0s 7ms/step - loss: 0.1920 - accuracy: 1.0000
Epoch 2503/5000
1/1 [==============================] - 0s 17ms/step - loss: 0.1919 - accuracy: 1.0000
Epoch 2504/5000
1/1 [==============================] - 0s 7ms/step - loss: 0.1918 - accuracy: 1.0000
Epoch 2505/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.1916 - accuracy: 1.0000
Epoch 2506/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.1915 - accuracy: 1.0000
Epoch 2507/5000
1/1 [==============================] - 0s 12ms/step - loss: 0.1913 - accuracy: 1.0000
Epoch 2508/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.1912 - accuracy: 1.0000
Epoch 2509/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.1910 - accuracy: 1.0000
Epoch 2510/5000
1/1 [================

In [11]:
xor.get_weights()

[array([[ 2.8520248, -3.028489 ],
        [ 2.7629998, -3.2428901]], dtype=float32),
 array([-3.6897957,  4.386321 ], dtype=float32),
 array([[ 4.412845],
        [-5.340634]], dtype=float32),
 array([-0.5365046], dtype=float32)]

In [12]:
xor.predict(x)

array([[0.00332171],
       [0.03439039],
       [0.03071567],
       [0.9315491 ]], dtype=float32)

In [14]:
from sklearn.datasets import load_breast_cancer
Data= load_breast_cancer()

In [15]:
print(Data.DESCR)


.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [16]:
features= Data.data
target= Data.target
print(features.shape)
print(target.shape)

(569, 30)
(569,)


In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(features, target, test_size=0.2)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(455, 30)
(455,)
(114, 30)
(114,)


In [35]:
from keras.models import Sequential 
from keras.layers import Dense

In [36]:
model= Sequential()

In [43]:
model.add(Dense(32, input_dim=30, activation= 'relu'))
model.add(Dense(64, activation= 'relu'))
model.add(Dense(1, activation='sigmoid'))

In [44]:
model.compile( loss='binary_crossentropy', optimizer='adam', metrics= ['accuracy'])

In [45]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 32)                992       
_________________________________________________________________
dense_3 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_4 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_5 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_6 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_7 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 6

In [46]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
15/15 [==============================] - 5s 2ms/step - loss: 0.6600 - accuracy: 0.6216
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6131 - accuracy: 0.6088
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.4482 - accuracy: 0.8899
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8932
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3557 - accuracy: 0.8746
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2678 - accuracy: 0.9002
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2651 - accuracy: 0.9000
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2463 - accuracy: 0.8836
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2786 - accuracy: 0.8881
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2470 - accuracy: 0.9144


In [25]:
scores=model.evaluate(x_test, y_test)
print(scores)

NameError: ignored

In [47]:
predictions = model.predict(x_test)
label=[]
for pred in predictions:
  if pred >=0.5:
    print("Malignent")
  else:
    print("Benign")

Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent